### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by drgagi** [pwitab/nbiot#1]
Hi,

Could you provide some useful example about how to use this NB IOT scanner tool? Do you have some guideline/documentation about it? 

Thanks.

**Comment by Krolken** [comment]
Yeah, I really should :) 
I have a branch for UDP messaging support via Command line that I should merge too.

But if you install it and run `nbiot --help` you should get the click command instructions on how to use the CLI.

```shell
 nbiot --help
Usage: nbiot [OPTIONS] COMMAND [ARGS]...

  This is a NB IoT Scanner software built by Palmlund Wahlgren Innovative
  Technology AB in Sweden for use in finding problems and evaluating network
  coverage in smart meter rollouts.

Options:
  -p, --port TEXT                 Register the serial port to use
  --roaming / --home-network      Indicate if the MNO is using home network or
                                  roaming status
  --mno TEXT                      ID of MNO (Mobile Network Operator) ex.
                                  Telia Sweden = 24001
  -l, --loglevel [DEBUG|INFO|WARNING]
                                  Choose loglevel
  --psm                           If Power Save Mode should be used.
  --apn TEXT                      choose apn
  --help                          Show this message and exit.

Commands:
  connect  The scan command enables you to connect and get information of...
  ping
  reboot
  send
  stats
```

The project assumes that you have a Ublox NB-IoT module. There is support for SARA-N2 and SARA-R4. But I'm thinking about dropping SARA-R4. It does not give you as much statistics. but you can use it with LTE-M.

I use a Sodaq board with a SARA-N211: https://shop.sodaq.com/sodaq-sara-aff-n211.html
You just need to load in a forwarding program in the Arduino chip.

**Comment by drgagi** [comment]
Hi,

Thank you for your response. I am using Sodaq NBIOT IoT shield with Leonardo board on port 14 but am not able make connection. See second issue I have posted. I have passthrough sketch and it works with putty serial.

**Comment by drgagi** [comment]
It is UBLOX N211 module on the board.

**Comment by Krolken** [comment]
I added a separate issue for docs so closing this one.
